### ISSUE TITLE
RoboCopy can't handle backslashes if the is a space in the path.

### ISSUE THREAD

**Issue by gerane** [RamblingCookieMonster/PSDeploy#42] opened 2016-06-16 17:18 UTC
Here are 3 tests I made to test it.

``` powershell
Deploy {
    By Filesystem {
        FromSource 'C:\Github\PSDeploy\PSDeploy'
        To 'C:\TestPSDeploy\Test Space\PSDeploy'
        Tagged Space
        WithOptions @{
            Mirror = $true
        }
    }

    By Filesystem {
        FromSource 'C:\Github\PSDeploy\PSDeploy'
        To 'C:\TestPSDeploy\Test Space\PSDeploy\'
        Tagged SpaceBackSlash
        WithOptions @{
            Mirror = $true
        }
    }

    By Filesystem {
        FromSource 'C:\Github\PSDeploy\PSDeploy\'
        To 'C:\TestPSDeploy\BackSpash\PSDeploy\'
        Tagged BackSlash
        WithOptions @{
            Mirror = $true
        }
    }
}
```

I've encountered this in another module of mine, and currently working on adding the fix over. Will try to add a few Pester tests too to make sure it is handling them properly.

**Comment by RamblingCookieMonster** [comment] 2016-06-16 17:53
Yep, there's no quotes around the source or target paths, that's no good.  Thanks for finding this!

**Comment by gerane** [comment] 2016-06-16 19:47
Thats actually not the problem, Robocopy just doesn't like trailing backslashes for Source and Destination. You can invoke robocopy directly like so

``` powershell
ROBOCOPY.exe 'C:\somepath\to\files' 'C:\some\other\path with\Space\'
```

Even though you have quotes, it fails. 

I have a fix finished, and tests written for FileSystem, but not quite sure if I can test RemoteFileSystem, so may leave it as is until I can look into it further.

**Comment by gerane** [comment] 2016-06-16 19:51
Though, there may be other scenarios where it might break in it's current form. I need to make a new test with both paths having spaces and see what happens.

In a module that I have where I was working with Robocopy, I was adding quotes, but I can't exactly remember where that breaks. Below is what I had, but I may have added that before I realized it was actually caused by the trailing backslash.

``` powershell
        $arguments += '"' + $Source + '"'
        $arguments += '"' + $Destination + '"'
```

**Comment by FooBartn** [comment] 2016-09-04 05:20
In your example, @gerane, I think you can either remove the trailing slash or use the robocopy syntax to escape it

ROBOCOPY.exe 'C:\somepath\to\files' 'C:\some\other\path with\Space'

OR

ROBOCOPY.exe 'C:\somepath\to\files' 'C:\some\other\path with\Space\/'

It seems like you could match on any path that included a space, and then make sure the trailing slash is either removed or escaped. Do you think that would work?

**Comment by FooBartn** [comment] 2016-09-04 20:16
New Invoke-Robocopy:
https://github.com/FooBartn/PSDeploy/blob/master/PSDeploy/Private/Invoke-Robocopy.ps1

Tests
https://github.com/FooBartn/PSDeploy/commit/24b3029a002b0ec36c2d04d9f16f1f325a212c71

Added in a little regex to remove any trailing slashes on paths, and wrote a new test for path with spaces. Are there any issues you can think of with doing it this way?

**Comment by FooBartn** [comment] 2016-09-04 20:24
Updated test to include spaces on both path and destination
https://github.com/FooBartn/PSDeploy/commit/1fd60f97b243490f0f1a8053e1d8a7e9db7ae9e6

**Comment by seandockery** [comment] 2016-09-05 16:41
> Thats actually not the problem, Robocopy just doesn't like trailing backslashes for Source and Destination. 

I've run into this previously.  It is the PowerShell parser having difficulty parsing up parameters rather than RoboCopy.exe.  You'll find that running the same command from Command Prompt runs without error.  One of the problems that this causes is that it is difficult (impossible?) to pass arguments to an external program where one of the parameters is meant to have a trailing backslash.

**Comment by FooBartn** [comment] 2016-09-19 21:41
@RamblingCookieMonster might be able to close now? This should be resolved with the last PR

**Comment by RamblingCookieMonster** [comment] 2017-01-08 23:06
Yep, closing this out, thanks for finding and tackling this all!

**Closed as completed by RamblingCookieMonster** 2017-01-08 23:06 UTC

**Comment by mklement0** [comment] 2017-08-18 04:02
@seandockery:

> it is difficult (impossible?) to pass arguments to an external program where one of the parameters is meant to have a trailing backslash.

Indeed needlessly difficult, but not impossible - see https://github.com/PowerShell/PowerShell/issues/4358#issuecomment-318528600

Hopefully - given that the issue is classified as a bug - the need for the `\\` workaround will go away.
